package pluginapi

import (
	"context"
	"time"
)

// FrameType classifies media stream frames in the 18-byte binary header.
type FrameType uint8

const (
	FrameTypeStreamStart FrameType = 0 // first frame; payload is JSON stream metadata
	FrameTypeVideoKey    FrameType = 1 // independent keyframe
	FrameTypeVideoDelta  FrameType = 2 // delta frame (requires preceding keyframe)
	FrameTypeAudio       FrameType = 3 // audio frame
	FrameTypeMetadata    FrameType = 4 // additional metadata (JSON payload)
	FrameTypeStreamEnd   FrameType = 5 // ordered stream end signal
)

// StreamEmitter is provided to StreamProducer.OnStart.
// For structured streams use EmitData; for media streams use EmitFrame.
type StreamEmitter interface {
	// EmitData sends an opaque protobuf payload on a structured (gRPC) stream.
	EmitData(payload []byte) error
	// EmitFrame writes a raw media frame (header auto-generated by the SDK) to
	// the plugin's media Unix socket.
	EmitFrame(frameType FrameType, ptsNs int64, payload []byte) error
}

// StreamProducer registers lifecycle hooks for a declared stream.
// The SDK calls OnStart when Core sends StartStreamCommand and cancels ctx
// when Core sends StopStreamCommand. OnStop is called after ctx cancellation.
type StreamProducer struct {
	// OnStart is called in a dedicated goroutine. ctx is cancelled on StopStream.
	OnStart func(ctx context.Context, emitter StreamEmitter)
	// OnStop is called after ctx cancellation for resource cleanup.
	// May be nil.
	OnStop func()
}

// StreamStats holds per-producer emission statistics tracked by the SDK.
type StreamStats struct {
	BytesEmitted  uint64
	FramesEmitted uint64
	FramesDropped uint64
	LastEmitAt    time.Time
	State         string // "idle" | "streaming"
}
